"""Types for celld's built-in Monty runtime."""
import builtins
from datetime import datetime, timedelta
from types import TracebackType
from typing import TypeAlias

Json: TypeAlias = None | bool | int | float | str | list["Json"] | dict[str, "Json"]
SqlValue: TypeAlias = None | bool | int | float | str

class Storage:
    def set(self, key: str, value: Json) -> None: ...
    def delete(self, key: str) -> bool: ...
    def get(self, key: str, default: Json = None) -> Json: ...
    def list(self, prefix: str = "", *, limit: int = 1000, reverse: bool = False) -> dict[str, Json]: ...
    def clear(self) -> None: ...
    def sql(self, query: str, *bindings: SqlValue) -> builtins.list[dict[str, SqlValue]]: ...
    def sync(self) -> None: ...
    def transaction(self) -> _Transaction: ...

class _Transaction:
    def __enter__(self) -> Storage: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool: ...

class Alarms:
    def get(self) -> datetime | None: ...
    def set(self, when: datetime | timedelta) -> None: ...
    def delete(self) -> None: ...

class Request:
    method: str
    url: str
    headers: dict[str, str]

class Response:
    body: str | bytes
    status: int
    headers: dict[str, str]
    def __init__(self, body: str | bytes = "", *, status: int = 200, headers: dict[str, str] | None = None) -> None: ...
    def text(self) -> str: ...
    def json(self) -> Json: ...

class Context:
    id: str | None
    env: dict[str, str]
    request: Request
    storage: Storage
    alarms: Alarms
    async def fetch(self, url: str, *, method: str = "GET", headers: dict[str, str] | None = None, body: str | bytes | None = None) -> Response: ...
    async def sleep(self, seconds: float) -> None: ...
    def now(self) -> datetime: ...
    def uuid(self) -> str: ...
    def log(self, message: str) -> None: ...
